#####################################################################################################
# This file only contains the default configuration!                                                #
# Environment-specific settings should be placed in a application-[dev|prod|test].yml file          #
# or by using OS environment variables. For more information on how to configure Spring see         #
# https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html #
#####################################################################################################
SUB_URL: "/submissions"

hydra:
  url: http://127.0.0.1:4444
  redirect: http://127.0.0.1:4444

spring:
  profiles:
    # The application runs in dev mode by default! Override this in production mode!
    active: dev
  batch:
    job:
      enabled: false
    initialize-schema: always
  data.ldap.repositories.enabled: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  liquibase:
    change-log: classpath:db/changelog-master.yaml
  security:
      oauth2:
        client:
          registration:
            hydra:
              client-name: Hydra
              scope: openid,offline
              client-id: auth-code-client
              client-secret: secret
              authorization-grant-type: authorization_code
              redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
          provider:
            hydra:
              authorization-uri: ${hydra.redirect}/oauth2/auth
              token-uri: ${hydra.url}/oauth2/token
              user-info-uri: ${hydra.url}/userinfo
              jwk-set-uri: ${hydra.url}/.well-known/jwks.json

logging:
  level:
    # root: DEBUG
    # Hides HHH000424: Disabling contextual LOB creation as createClob() method threw error
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN
    # Hide log spam of docker pull progress
    com.spotify.docker.client.LoggingPullHandler: WARN
    graphql.execution.SimpleDataFetcherExceptionHandler: ERROR

graphql:
  packages:
    - "org.codefreak.codefreak.graphql.api"

server:
  servlet:
    context-path: ${SUB_URL:}
    session:
      # Set server-side timeout of cookies
      # The client session-cookie will expire on browser close by default
      timeout: 24h
  port: 8080
  use-forward-headers: true

codefreak:
  #authenticationMethod: 0
  instanceId: default
  authorities:
    oAuth2:
      # Authority management of oAuth2 to define admin and teacher accounts
      '[foo@bar.com]': admin
  files:
    adapter: jpa_hdd
  docker:
    # All of the docker settings below will fall back to a system-depended default value if unset
    host: ~
    certPath: ~
    caCertPath: ~
    clientKeyPath: ~
    clientCertPath: ~
    # Define how (and if) images will be pulled on application startup
    pull-policy: always
  ide:
    image: "cfreak/ide:1"
    # Interval for checking for idle containers in ms. Default 30 seconds.
    idle-check-rate: 30000
    # Time span after which an idle container is shut down. Default 1 minute.
    idle-shutdown-threshold: 60000
    # Memory limit in bytes (2GiB)
    memory: 2147483648
    # Number of CPUs per container (0 means no limit)
    cpus: 0
    # Name of the network the container will be attached to
    network: bridge
    httpPort: 3000
# Enable actuator health checks if needed in production
# https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator-properties
management:
  health:
    defaults:
      enabled: false
